[package]
name = "sync-es-openobserve"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive", "env"] }
elasticsearch = "8.17.0-alpha.1"
reqwest = "0.12.15"
serde_json = "1.0.140"
tokio = "1.44.1"
